### ISSUE TITLE
Events link to the old plenum page and plenum list

### ISSUE THREAD

**Issue by serverwentdown** [hackerspacesg/hackerspace.sg#178]
See the events list on the homepage: hackerspace.sg
It links to https://hackerspace.sg/plenum/
Should redirect to the new plenums page: https://docs.hackerspace.sg/plenum/

**Comment by valentine** [comment]
The redirects seem to have finally been fixed in https://github.com/hackerspacesg/hackerspace.sg/commit/46ddf29137d8e5d96a981a6977a3a3b64a7158b5.

Cloudlfare Pages doesn't support forcing redirects with `301!`, which was probably why the earlier redirects to the docs page didn't work.

As for the events list, they're autogenerated from [our Events Booking Google Calendar](https://www.google.com/calendar/ical/mengwong%40hackerspace.sg/public/basic.ics), so I guess I'll have to change the links there…
